### PR TITLE
Make it compatible with Node 10.0 - 10.7

### PR DESCRIPTION
**Pull request by mildsunrise**
Turns out it was easy :)

However, I had to patch binding.gyp as indicated [here](https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL), otherwise the code used system OpenSSL headers instead of Node.JS version of OpenSSL.

### CODE REVIEW

**Comment by mildsunrise** [comment]
Aaaand it turns out this is also happening in Travis. I'll take a look.

**Comment by mildsunrise** [comment]
It's a bug in node-gyp that was [fixed](https://github.com/nodejs/node-gyp/pull/1055) in node-gyp 3.7.0.
Node.JS 10.0 only has node-gyp 3.6.2.

**Comment by mildsunrise** [comment]
I've ended up backporting the fix (it's two includes)

**Comment by kolontsov** [comment]
Great work! it compiles and runs simple tests.

However I have concerns about `&(*ssl_)` (which makes code compatible with both `SSL*` and `std::unique_ptr<SSL>`), because `operator*` has undefined behaviour if `get()` returns nullptr, or if we're dereferencing NULL SSL* pointer. In our case it seems to work with null pointer because we use `&*`, but.. can we please switch to `#ifdef` or something like this, to use `return ssl_` for <=10.7 and `return ssl_.get()` in other cases?

**Comment by mildsunrise** [comment]
Done!

**Pull request merged**
